<?php

/**
 * DetallePedidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetallePedidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetallePedidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DetallePedido');
    }
}