<?php

/**
 * PedidoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PedidoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PedidoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Pedido');
    }
}