<?php

/**
 * TwittBaseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TwittBaseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TwittBaseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TwittBase');
    }
}