<?php

/**
 * CouponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CouponTable extends PluginCouponTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object CouponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Coupon');
    }
}