<?php

/**
 * TaxTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxTable extends PluginTaxTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tax');
    }
}